### ISSUE TITLE
Doc's misspelled command for install 

### ISSUE THREAD

**Issue by maxvanceffer** [sonrisesoftware/project-dashboard#108]
In main read me you have misspelled command for add ppa:

Your raw:
  sudo apt-get add-apt-repository ppa:ubuntu-touch-community-dev/ppa

But should be: 
  sudo apt-add-repository ppa:ubuntu-touch-community-dev/ppa

**Comment by krnekhelesh** [comment]
Thanks for the bug report. I have a fix for this in my pull request.

**Comment by krnekhelesh** [comment]
This issue is fixed as well
