### ISSUE TITLE
[Github] Pull request title overlapping icon

### ISSUE THREAD

**Issue by krnekhelesh** [sonrisesoftware/project-dashboard#109]
If you look at https://imgur.com/rH7a2pb, you will notice that the pull request #105 title is overlapping with the error icon. This is because the width of the listitem title is parent.width. It doesn't take into account the presence of the icon.

**Comment by krnekhelesh** [comment]
I have a fix for this in my lastest pull request #105

**Comment by iBelieve** [comment]
@krnekhelesh, I set up a Contributors team and added you to it, which gives you the ability to assign issues to yourself. I've also assigned the three issues you fixed in your pull request to yourself.

**Comment by krnekhelesh** [comment]
@iBeliever, ah thanks...these issues now appear in my Pulse...looks pretty cool.

**Comment by iBelieve** [comment]
Same problem, the pull request didn't close or reference this.
