### ISSUE TITLE
[Github] Clicking on bug link should open bug page

### ISSUE THREAD

**Issue by krnekhelesh** [sonrisesoftware/project-dashboard#110]
Currently bug links which are shown in pull requests like #108 etc, are hyperlinks i.e they open in a browser when you click them. However why can't we instead take the bug number and use that information to open the respective issue page in Project Dashboard itself instead of showing a web page? This will make it a more pleasant user experience.

**Comment by krnekhelesh** [comment]
@iBeliever , Do you mind if I take this bug? I am unable to assign the bug to me both in Github and Project Dashboard.

**Comment by iBelieve** [comment]
@krnekhelesh, sure, go ahead! I'm not sure why you can't assign bugs to yourself. I'll look into it.
