### ISSUE TITLE
[Github] Pull request show incorrect information

### ISSUE THREAD

**Issue by krnekhelesh** [sonrisesoftware/project-dashboard#111]
If you look at the pull request page at https://imgur.com/B6S9sS9 you will notice the following mistakes,
- It says "user wants to merge 0 commits" but clearly it is not 0 commits
- It doesn't the show the commit history that github normally shows in the pull request page.
- It doesn't show the comments made in the pull request page

**Comment by iBelieve** [comment]
This will land in v0.5, which I will publish as soon as I merge your branch.

**Comment by krnekhelesh** [comment]
Yup this works nicely as expected. Now I don't need to go to Github pull request page to read the comments and commit history.
