### ISSUE TITLE
The OSK is displayed when opening an issue

### ISSUE THREAD

**Issue by krnekhelesh** [sonrisesoftware/project-dashboard#77]
Every time I open an issue, the OSK appears and takes half of the phone screen. Many times I open an issue to just see more details about it. It would be better to not give any input focus to the text field so that the OSK is not shown when opening an issue.

http://imgur.com/I15jH7Y

**Comment by iBelieve** [comment]
This is why it's so helpful to have people with devices test my apps (and why I really need to get an Nexus to use & test my own apps :).

I had no idea the text field is getting focus. It shouldn't be - it's read only.

**Comment by iBelieve** [comment]
And while I'm thinking about it, in cased you didn't see what I said on IRC, the issue page should not be showing the JSON - I did that for debugging only and accidentally committed it and forgot about it.

**Comment by krnekhelesh** [comment]
I am sorry, but I am not sure what JSON you are referring to. Could you elaborate on that?

**Comment by iBelieve** [comment]
Nevermind - it's not showing in the screenshot you sent - I must have changed it before I made the second click.
