### ISSUE TITLE
Connection error dialog keeps popping up

### ISSUE THREAD

**Issue by krnekhelesh** [sonrisesoftware/project-dashboard#79]
I keep getting the error dialog "Connection Error" as seen in the screenshot 
http://imgur.com/5rnvnWG. I have observed the following,
1. Disabling and then re-enabling the Github didn't help
2. The error doesn't appear immediately. Sometimes I lock the screen and come back to the app few minutes later when I see it.
3. I have 4 issues in my Github project and I noticed that I have to press the error dialog button 4 times to close the dialog. Coincidence? I think not. Somewhere while retrieving the issues it gets a error perhaps? 

I know without console output, it is difficult to point out the issue. Perhaps you can let me know if you need any other info to help fix this bug.

**Comment by iBelieve** [comment]
I've created a new click package that includes the http request that failed when displaying an error message:

http://ubuntuone.com/2i9tHUrM83kaC2XGCN4VR3

**Comment by krnekhelesh** [comment]
I do not see the errors anymore, however now I see the following message https://imgur.com/0JgEzXU. This is with v0.4. Unfortunately I do not have other github projects to exactly try it out with :P

**Comment by iBelieve** [comment]
The next version to land in the store will let you click error messages to display the full path of the call and the response that was received.

What is weird is that the response is a 410, which means that the resource existed once but now no longer exists. Not sure what would be causing that.

**Comment by iBelieve** [comment]
Ok, the new version has landed in the store so it would be great if you could click on the error in the sync popover and take a screenshot so I can see the API call & the response received.

**Comment by iBelieve** [comment]
(I messed up with the Debian changelog so it hasn't landed in the PPA yet).

**Comment by krnekhelesh** [comment]
I will just clone your code and run it on the desktop :) ... I dont need PPA or click store update.

**Comment by iBelieve** [comment]
Since it seems like this is fixed for you (and the forked project problem is part of another issue), I'm going to close this now
