### ISSUE TITLE
Pulse wording seems a bit ambigious

### ISSUE THREAD

**Issue by krnekhelesh** [sonrisesoftware/project-dashboard#80]
I am not sure what the wording "Pulse" refers. Does it shows the tasks concerning the user?

**Comment by iBelieve** [comment]
Yes, it shows issues assigned to the user, open pull requests, the amount of time tracked today, upcoming events, etc.

The name came from the slightly similar GitHub Pulse feature (when you click the heart-rate/line graph icon on the right side of a project). 

Maybe naming the two tabs "Overview" and "Details" would be better?

**Comment by iBelieve** [comment]
Now that I've added the initial walkthough (which explains what Pulse is), do you still think there is a better to label these tabs?

**Comment by krnekhelesh** [comment]
I think Pulse can stay now that you have an awesome initial walkthrough. So this bug can be closed.
