### ISSUE TITLE
Notes with an ampersand ('&') in the title aren't displayed correctly in the notes list

### ISSUE THREAD

**Issue by nikwen** [sonrisesoftware/project-dashboard#84]
The rest of the title, the description and the date aren't displayed in the notes list.

**Comment by iBelieve** [comment]
The reason is because the list item is using HTML to achieve the green date label and thus the `&` symbol was being interpreted as the start of HTML special character.

Thanks for catching this, I'll figure out a way to fix it.

**Comment by nikwen** [comment]
Thanks.
