### ISSUE TITLE
Start in a bigger window on the desktop

### ISSUE THREAD

**Issue by nikwen** [sonrisesoftware/project-dashboard#85]
In my opinion it should at least be:

`width: units.gu(100)
height: units.gu(75)`

**Comment by iBelieve** [comment]
I've been using the current height and width for testing since it's the size of the Nexus 4 and I've been using a mobile-first strategy to make sure the app works well on small screen sizes.

I'll change it make to a desktop size.

**Comment by iBelieve** [comment]
This should land in the PPA hopefully later this evening.

**Comment by nikwen** [comment]
Great, thanks.

Maybe you can find a way to distinguish between release and test builds.
