### ISSUE TITLE
Unable to add events

### ISSUE THREAD

**Issue by krnekhelesh** [sonrisesoftware/project-dashboard#88]
I enabled the events plugin and then proceeded to add a new event to my Github project. On clicking the add event button, I can see the add event sheet. However after entering the event name and date, pressing the ok and cancel button does nothing. As a result, I am unable to hide the sheet. The only way to recover is to restart the app!

This is quite critical. Please fix ASAP.

**Comment by iBelieve** [comment]
Forgot to close this from the commit. I'm uploading the fix to the store and PPA right now.
