### ISSUE TITLE
Events shows the wrong number of remaining days

### ISSUE THREAD

**Issue by krnekhelesh** [sonrisesoftware/project-dashboard#90]
Today is 7th April. I created an event on the 8th April. However the event is still shown as **0 Days**. Considering that the user cannot enter the time while creating an event, the absolute difference between the start date and end date should be used.

https://imgur.com/2fgHZOC

**Comment by iBelieve** [comment]
That's what should be happening. Not sure why it didn't work.

**Comment by iBelieve** [comment]
This should be fixed now
