### ISSUE TITLE
About page layout broken in landscape

### ISSUE THREAD

**Issue by nikwen** [sonrisesoftware/project-dashboard#92]
The Icon appears behind the header. The content is not scrollable. (Nexus 4)

**Comment by iBelieve** [comment]
Can you attach a screenshot? I'm not sure how it could be happening since I've been testing the app with the exact size of a N4 it's looked fine.

**Comment by krnekhelesh** [comment]
N4 Screenshots

Portrait - http://imgur.com/9fMIYVv
Landscape - http://imgur.com/peNRI4B 

The bug is in the landscape interface.

**Comment by iBelieve** [comment]
Duh, I totally missed that the title said "Landscape". Thanks for the screenshot, Nik.

**Comment by nikwen** [comment]
Thanks to @krnekhelesh and @iBeliever.
