### ISSUE TITLE
Sidebar in desktop mode does not respond to clicks

### ISSUE THREAD

**Issue by krnekhelesh** [sonrisesoftware/project-dashboard#94]
I got an update to v0.4.2 via the PPA where a new sidebar appeared in the desktop mode. https://imgur.com/JP7sTJj. However clicking on the items in the sidebar does nothing. What is the purpose of this sidebar?

**Comment by iBelieve** [comment]
Ugh, that was just some experimental code and was never supposed to be published. I was thinking that it wouldn't show up since I hadn't committed it to git, but I do my builds from my working directory so it still got in. I'll take it out in the next build ((it's already gone from the app store).

**Comment by krnekhelesh** [comment]
Yeah you need to be more careful in the future

**Comment by iBelieve** [comment]
Well, at least I learned the lesson before I uploaded something really broken and deleted all my users data.

Closing now as the PPA accepted the next version.
